# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 19:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeStampedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.TimeStampedModel')),
                ('active', models.BooleanField(default=True)),
                ('role', models.CharField(choices=[('NU', 'Normal User'), ('VU', 'VIP'), ('EU', 'Entreprise'), ('SU', 'Staff'), ('AU', 'Admin')], default='NU', max_length=2)),
            ],
            bases=('users.timestampedmodel',),
        ),
        migrations.CreateModel(
            name='ProfilePreferences',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.TimeStampedModel')),
                ('option1', models.BooleanField(default=True)),
            ],
            bases=('users.timestampedmodel',),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferences',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ProfilePreferences'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
