# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilerequest',
            name='status',
            field=models.CharField(choices=[(1, 'Active Request'), (0, 'Request responded')], default=1, max_length=2),
        ),
    ]
