# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profilerequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilerequest',
            name='status',
            field=models.CharField(choices=[('1', 'Pending Request'), ('0', 'Request responded')], default='1', max_length=1),
        ),
    ]
