# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20171016_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.TimeStampedModel')),
                ('name', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('image', models.ImageField(null=True, upload_to=b'')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
            ],
            bases=('users.timestampedmodel',),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.TimeStampedModel')),
                ('name', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(null=True, upload_to=b'')),
                ('admins', models.ManyToManyField(blank=True, related_name='admins', to='users.Profile')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
                ('members', models.ManyToManyField(blank=True, related_name='members', to='users.Profile')),
            ],
            bases=('users.timestampedmodel',),
        ),
        migrations.CreateModel(
            name='InterestTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('tags', models.ManyToManyField(related_name='interest_tag', to='users.InterestTag')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileRequest',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.TimeStampedModel')),
                ('message', models.CharField(max_length=50)),
                ('reason', models.CharField(choices=[('FL', 'Invitation so you could see users Activity.'), ('FR', 'Invitation to become Friends.'), ('EV', 'Invitation to an Event.'), ('GR', 'Invitation to become part of a Group.'), ('OR', 'Invitation to become part of an Organization.'), ('EN', 'Invitation to become part of an Enterprise.')], max_length=2)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
                ('sugested_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='users.Event')),
                ('sugested_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='users.Group')),
                ('sugested_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sugested', to='users.Profile')),
            ],
            bases=('users.timestampedmodel',),
        ),
        migrations.AddField(
            model_name='event',
            name='invited',
            field=models.ManyToManyField(blank=True, related_name='invited', to='users.ProfileRequest'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizers',
            field=models.ManyToManyField(blank=True, related_name='organizers', to='users.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='envents', to='users.Event'),
        ),
        migrations.AddField(
            model_name='profile',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='groups', to='users.Group'),
        ),
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='interests', to='users.ProfileInterest'),
        ),
        migrations.AddField(
            model_name='profile',
            name='requests',
            field=models.ManyToManyField(blank=True, related_name='requests', to='users.ProfileRequest'),
        ),
    ]
