# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20171027_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilerequest',
            name='status',
            field=models.CharField(choices=[('1', 'Pending Request'), ('0', 'Request Responded'), ('2', 'Request Canceled')], default='1', max_length=1),
        ),
    ]
