# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 02:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20171016_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='invited',
            field=models.ManyToManyField(blank=True, related_name='event_invited', to='users.ProfileRequest'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizers',
            field=models.ManyToManyField(blank=True, related_name='event_organizers', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='group',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='group_admins', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='group_members', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='profile_envents', to='users.Event'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='profile_folowers', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='profile_folowing', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='profile_groups', to='users.Group'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='profile_interests', to='users.ProfileInterest'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='requests',
            field=models.ManyToManyField(blank=True, related_name='profile_requests', to='users.ProfileRequest'),
        ),
        migrations.AlterField(
            model_name='profilerequest',
            name='sugested_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_event_sugested', to='users.Event'),
        ),
        migrations.AlterField(
            model_name='profilerequest',
            name='sugested_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_group_sugested', to='users.Group'),
        ),
        migrations.AlterField(
            model_name='profilerequest',
            name='sugested_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_user_sugested', to='users.Profile'),
        ),
    ]
