# Generated by Django 2.0.2 on 2018-04-24 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memberits', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberit',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
        migrations.AddField(
            model_name='memberit',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='memberit_tag', to='users.InterestTag'),
        ),
    ]
