# Generated by Django 2.0.2 on 2018-04-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180423_2159'),
        ('memberits', '0002_memberit_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberit',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='memberit_tag', to='users.InterestTag'),
        ),
    ]
