# Generated by Django 2.0.2 on 2018-04-23 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberits', '0003_memberit_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberit',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='memberit_tag', to='users.InterestTag'),
        ),
    ]
