# Generated by Django 2.0.2 on 2018-04-24 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberits', '0004_auto_20180423_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberit',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
