# Generated by Django 2.0.2 on 2018-04-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='event_tag', to='users.InterestTag'),
        ),
        migrations.AlterField(
            model_name='profileinterest',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='interest_tag', to='users.InterestTag'),
        ),
    ]
