# Generated by Django 2.0.1 on 2018-01-10 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20171124_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preferences',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.ProfilePreferences'),
        ),
        migrations.AlterField(
            model_name='profilemessagehistory',
            name='profile1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile1', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='profilemessagehistory',
            name='profile2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile2', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='profilerequest',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='profilerequest',
            name='sugested_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='request_event_sugested', to='users.Event'),
        ),
        migrations.AlterField(
            model_name='profilerequest',
            name='sugested_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='request_group_sugested', to='users.Group'),
        ),
        migrations.AlterField(
            model_name='profilerequest',
            name='sugested_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='request_user_sugested', to='users.Profile'),
        ),
    ]
