# Generated by Django 2.0.2 on 2018-03-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180110_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilerequest',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
