# Generated by Django 2.0.2 on 2018-04-23 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_event_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_home', models.CharField(default='0', max_length=3)),
                ('score_away', models.CharField(default='0', max_length=3)),
                ('limit_date', models.DateField(blank=True, null=True)),
                ('match_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quiniela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('description', models.CharField(default='', max_length=150)),
                ('members', models.ManyToManyField(related_name='quiniela_members', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(related_name='quiniela_tag', to='users.InterestTag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('history', models.CharField(default='', max_length=150)),
                ('tags', models.ManyToManyField(related_name='team_tag', to='users.InterestTag')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('description', models.CharField(max_length=150, unique=True)),
                ('start_in', models.DateField(blank=True, null=True)),
                ('ends_in', models.DateField(blank=True, null=True)),
                ('tags', models.ManyToManyField(related_name='tournament_tag', to='users.InterestTag')),
            ],
        ),
        migrations.AddField(
            model_name='quiniela',
            name='tournaments',
            field=models.ManyToManyField(related_name='quiniela_tournamets', to='quiniela.Tournament'),
        ),
        migrations.AddField(
            model_name='game',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='quiniela.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='quiniela.Team'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='games',
            field=models.ManyToManyField(related_name='fixture_games', to='quiniela.Game'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_fixture', to='quiniela.Fixture'),
        ),
    ]
