# Generated by Django 2.0.2 on 2018-04-23 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiniela', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='tags',
            field=models.ManyToManyField(related_name='tournament_tag', to='users.InterestTag'),
        ),
        migrations.AddField(
            model_name='team',
            name='tags',
            field=models.ManyToManyField(related_name='team_tag', to='users.InterestTag'),
        ),
        migrations.AddField(
            model_name='quiniela',
            name='members',
            field=models.ManyToManyField(related_name='quiniela_members', to='users.Profile'),
        ),
        migrations.AddField(
            model_name='quiniela',
            name='tags',
            field=models.ManyToManyField(related_name='quiniela_tag', to='users.InterestTag'),
        ),
        migrations.AddField(
            model_name='quiniela',
            name='tournaments',
            field=models.ManyToManyField(related_name='quiniela_tournamets', to='quiniela.Tournament'),
        ),
        migrations.AddField(
            model_name='game',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='quiniela.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='quiniela.Team'),
        ),
    ]
