# Generated by Django 2.0.2 on 2018-06-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiniela', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiniela',
            name='quiniela_type',
            field=models.CharField(choices=[('TQ', 'Predict all games and scores.'), ('PQ', 'Predict just current phase games and scores.')], default='EA', max_length=2),
        ),
        migrations.AddField(
            model_name='quiniela',
            name='quiniela_type_cache',
            field=models.CharField(choices=[('TQ', 'Predict all games and scores.'), ('PQ', 'Predict just current phase games and scores.')], default='EA', editable=False, max_length=2),
        ),
    ]
