# Generated by Django 2.0.2 on 2018-04-24 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('quiniela', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='members_results',
            field=models.ManyToManyField(related_name='members_fixture_games', through='quiniela.MemberFixture', to='users.Profile'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tournament_tag', to='users.InterestTag'),
        ),
        migrations.AddField(
            model_name='team',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='team_tag', to='users.InterestTag'),
        ),
        migrations.AddField(
            model_name='quiniela',
            name='members',
            field=models.ManyToManyField(related_name='quiniela_members', to='users.Profile'),
        ),
        migrations.AddField(
            model_name='quiniela',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='quiniela_tag', to='users.InterestTag'),
        ),
        migrations.AddField(
            model_name='quiniela',
            name='tournaments',
            field=models.ManyToManyField(related_name='quiniela_tournamets', to='quiniela.Tournament'),
        ),
        migrations.AddField(
            model_name='memberfixture',
            name='games',
            field=models.ManyToManyField(related_name='member_fixture_game_results', to='quiniela.Game'),
        ),
        migrations.AddField(
            model_name='memberfixture',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiniela.Tournament'),
        ),
        migrations.AddField(
            model_name='memberfixture',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
        migrations.AddField(
            model_name='gamecontext',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiniela.Game'),
        ),
        migrations.AddField(
            model_name='gamecontext',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiniela.Tournament'),
        ),
        migrations.AddField(
            model_name='game',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='quiniela.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='quiniela.Team'),
        ),
        migrations.AlterUniqueTogether(
            name='memberfixture',
            unique_together={('user', 'tournament')},
        ),
        migrations.AlterUniqueTogether(
            name='gamecontext',
            unique_together={('tournament', 'context')},
        ),
    ]
