# Generated by Django 2.0.2 on 2018-04-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiniela', '0002_auto_20180424_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='context',
            field=models.ManyToManyField(related_name='game_context', through='quiniela.GameContext', to='quiniela.Tournament'),
        ),
    ]
