# Generated by Django 2.0.2 on 2018-05-25 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiniela', '0003_oscarcoin'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiniela',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
