# Generated by Django 2.0.2 on 2018-04-23 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiniela', '0003_auto_20180423_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiniela',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='quiniela_tag', to='users.InterestTag'),
        ),
        migrations.AlterField(
            model_name='team',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='team_tag', to='users.InterestTag'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tournament_tag', to='users.InterestTag'),
        ),
    ]
