# Generated by Django 2.0.2 on 2018-04-24 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiniela', '0003_game_context'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiniela',
            name='tournaments',
        ),
        migrations.AddField(
            model_name='quiniela',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiniela.Tournament'),
        ),
    ]
