# Generated by Django 2.0.2 on 2018-04-23 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiniela', '0004_auto_20180423_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiniela',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
