# Generated by Django 2.0.2 on 2018-05-25 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiniela', '0004_quiniela_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiniela',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
