# Generated by Django 2.0.2 on 2018-04-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiniela', '0005_auto_20180424_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='limit_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='match_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
