# Generated by Django 2.0.2 on 2018-04-25 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiniela', '0006_auto_20180425_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='limit_date',
        ),
        migrations.RemoveField(
            model_name='game',
            name='match_date',
        ),
    ]
