# Generated by Django 2.0.2 on 2018-04-25 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiniela', '0007_auto_20180425_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='limit_datetime',
        ),
    ]
