# Generated by Django 2.0.2 on 2018-04-25 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiniela', '0011_auto_20180425_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberfixture',
            name='games_checked',
            field=models.IntegerField(default=0),
        ),
    ]
