# Generated by Django 2.0.2 on 2018-04-26 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiniela', '0012_memberfixture_games_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='score_set',
            field=models.BooleanField(default=False),
        ),
    ]
