# Generated by Django 2.0.2 on 2018-04-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiniela', '0014_auto_20180425_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiniela',
            name='score_type',
            field=models.CharField(choices=[('TO', 'Game Result Points.'), ('EA', 'Game Result and Teams Score Points.')], default='TO', max_length=2),
        ),
    ]
