# Generated by Django 2.0.2 on 2018-04-26 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiniela', '0018_quiniela_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiniela',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
    ]
