# Generated by Django 2.0.2 on 2018-04-27 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiniela', '0020_auto_20180426_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberfixture',
            name='quiniela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiniela.Quiniela'),
        ),
    ]
