# Generated by Django 2.0.2 on 2018-05-01 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiniela', '0024_auto_20180430_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='score_away',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='game',
            name='score_home',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='score_away',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='score_home',
            field=models.CharField(default='0', max_length=5),
        ),
    ]
